packages:
  - apps/*
  - packages/*
catalog:
  react: ^19.2.3
  react-dom: ^19.2.3
  vue: ^3.5.26
  lodash: ^4.17.21
  typescript: ^5.9.3
  eslint: ^9.39.2
  prettier: ^3.7.4
  "@rsbuild/core": ^1.7.1
  "@rsbuild/plugin-react": ^1.4.2
  "@rsbuild/plugin-vue": ^1.2.2
