packages:
  - apps/*
  - packages/*
catalog:
  '@eslint/js': ^9.39.2
  '@rsbuild/core': ^1.7.2
  '@rsbuild/plugin-react': ^1.4.2
  '@rsbuild/plugin-vue': ^1.2.2
  '@types/lodash': ^4.17.21
  '@typescript-eslint/eslint-plugin': ^8.52.0
  '@typescript-eslint/parser': ^8.52.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-vue: ^10.6.2
  lodash: ^4.17.21
  prettier: ^3.7.4
  react: ^19.2.3
  react-dom: ^19.2.3
  typescript: ^5.9.3
  typescript-eslint: ^8.52.0
  vue: ^3.5.26
  vue-eslint-parser: ^10.2.0
